### ISSUE TITLE
Include 1% and 0.1% lows in readme.md

### ISSUE THREAD

**Issue by MuffinTastic** [Greendayle/VRChat-benchmark-cache#1]
The data on display here is nice, but it doesn't show the whole story. 1% and 0.1% lows are the dips in framerate that you actually feel the most. I think it'd best if they were shown here too.

**Comment by Greendayle** [comment]
It already does in the frame timings histograms.

**Comment by MuffinTastic** [comment]
Ah, true.... I must've been really hyperfocused on the average and 95%/99% percentiles numbers and misinterpreted them. My bad. Closing

**Comment by Greendayle** [comment]
99% of frame time is equivalent of 1 percent low fps.
